tap "argon/mas"
tap "hashicorp/tap"
brew "direnv"
brew "gh"
brew "node", link: false
brew "node@24", link: true
brew "qpdf"
brew "rtk"
brew "tfenv"
brew "zsh-autosuggestions"
cask "battery"
cask "clipy"
cask "gcloud-cli"
cask "rectangle"
